### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by bamboo-foo** [LemmyOnukwugha/unit-3-assessment#1]
### Aggregate

⭐ Nice aggregation!

https://github.com/LemmyOnukwugha/unit-3-assessment/blob/751a440ea68862785f1949f4dc887c6329cd4163/main_app/views.py#L13

To stop the key showing in the template, we can get the value:

```python
    sum = Widget.objects.aggregate(Sum('quantity')).get('quantity__sum')
```

### Using the linked Pure css

The styles have been loaded correctly from the `<link>` in the head of our document, and we have all the classes in the linked [pure css file](https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure.css) available to us.

For example we have the `pure-button` class that we can add to a button:
```css
.pure-button {
    /* Structure */
    display: inline-block;
    line-height: normal;
    white-space: nowrap;
    vertical-align: middle;
    text-align: center;
    cursor: pointer;
    -webkit-user-drag: none;
    -webkit-user-select: none;
            user-select: none;
    box-sizing: border-box;
}
```

Then in our template:
https://github.com/LemmyOnukwugha/unit-3-assessment/blob/751a440ea68862785f1949f4dc887c6329cd4163/main_app/templates/home.html#L61

```html
      <button type="submit" class="btn pure-button">ADD WIDGET</button>
```

We also have `pure-form` `pure-table` and `pure-table-striped` classes.
